### PR TITLE
Heap sort python program added

### PR DESCRIPTION
**Pull request by NitikaGupta16**
#7

### CODE REVIEW

**Comment by neha07kumari** [comment]
Please resolve the conflicts.

**Comment by NitikaGupta16** [comment]
@neha07kumari  Conflicts are occurring due to changes in **Contributors.md** file. Every contributor changes this file due to which conflicts will always occur.

**Comment by NitikaGupta16** [comment]
> @neha07kumari Conflicts are occurring due to changes in **Contributors.md** file. Every contributor changes this file due to which conflicts will always occur except in the first PR you will merge every time.

**Comment by neha07kumari** [comment]
yes, I know.

**Comment by neha07kumari** [comment]
Resolve it now if you can .
As it can be resolved.

**Comment by NitikaGupta16** [comment]
> Resolve it now if you can . As it can be resolved.

Okay, I am doing it right now.

**Comment by neha07kumari** [comment]
Sure.

**Comment by NitikaGupta16** [comment]
> Sure.

Now, you can merge and for contributors.md I had send you a separate pull request.

**Comment by neha07kumari** [comment]
Good Work @NitikaGupta16 🎉

**Comment by neha07kumari** [comment]
Good Work @NitikaGupta16 🎉

**Pull request merged**
