### PR TITLE
Added Selection Sort Algorithm

### PR DESCRIPTION
**Pull request by silicolicious**
Issue: #1 

I have added the algorithm *Selection Sort* in python
Please review it and merge. Let me know if there is any problem.

Merge it with label hacktoberfest-accepted
Thank you!

### CODE REVIEW

**Comment by neha07kumari** [comment]
@silicolicious  You missed changing one file.
You also need to add some lines in contributors.md file
Do the needful.

**Comment by silicolicious** [comment]
@neha07kumari 
Which other file did I miss changing? Can you please tell me.


and also I need to add a line about myself in contributors.md, I'll do that.

**Comment by silicolicious** [comment]
@neha07kumari Thanks for informing me about it
I have successfully added about me in the contributors.md file.

Thank you!

**Comment by silicolicious** [comment]
Can you please merge it with the label hacktoberfest-accepted

**Comment by neha07kumari** [comment]
Good work @silicolicious 🎉

**Pull request merged**
