### PR TITLE
Added Youtube-Downloader

### PR DESCRIPTION
**Pull request by EitoZX**
A python program to easily download youtube videos & playlists.

### CODE REVIEW

**Comment by neha07kumari** [comment]
you need to make changes in contributor.md file also.

**Comment by EitoZX** [comment]
> you need to make changes in contributor.md file also.

Done. And Preview of Contributor.md is improved with some change.

**Comment by neha07kumari** [comment]
Please resolve the conflicts.

**Comment by EitoZX** [comment]
> Please resolve the conflicts.

Done

**Comment by neha07kumari** [comment]
Good work @EitoZX

**Comment by EitoZX** [comment]
Thanks @neha07kumari :)

**Pull request merged**
