### PR TITLE
Made a simple TicTacToe game using py game

### PR DESCRIPTION
**Pull request by SCHW18TZ**
Please accept my contribution I worked hard on it

### CODE REVIEW

**Comment by neha07kumari** [comment]
@SCHW18TZ  Please read the "rules& steps for contribution" in README.md

**Comment by neha07kumari** [comment]
you need to open up an issue and when assigned then go for PR.

**Comment by SCHW18TZ** [comment]
Okay  I will do it

**Comment by neha07kumari** [comment]
Do make necessary changes in contributors.md file. 
I'm closing this PR make a new PR.

**Pull request closed without merging**
