### PR TITLE
added fold fulkerson algo

### PR DESCRIPTION
**Pull request by mr-desilva**
😊 First pr for 2021 Hacktober

### CODE REVIEW

**Comment by neha07kumari** [comment]
@mr-desilva  Please go through the "rules for contribution" in the README.md .
Please make an issue first regarding your contribution and when assigned then go for the PR.
Hope you understood it.🙂

**Comment by mr-desilva** [comment]
Hi @neha07kumari  I have created a issue 😊

**Comment by neha07kumari** [comment]
Please follow all the steps for contribution from README.md
complete your step for contributors.md file

**Comment by mr-desilva** [comment]
Hi I have updated the Contributors.md ☺

**Comment by neha07kumari** [comment]
Good work @mr-desilva

**Pull request merged**
