### PR TITLE
Added Bubble_Sort Algorithum

### PR DESCRIPTION
**Pull request by Varun270**

### CODE REVIEW

**Comment by neha07kumari** [comment]
all is good. 
Please add your name in contributors.md file and push the changes.

**Comment by Varun270** [comment]
> all is good. Please add your name in contributors.md file and push the changes.

Should I create a separate PR for that or force push will do?

**Comment by neha07kumari** [comment]
> > all is good. Please add your name in contributors.md file and push the changes.
> 
> Should I create a separate PR for that or force push will do?

No need of making separate PR.
Force push will work.

**Comment by neha07kumari** [comment]
any issues after that let me know :)

**Comment by neha07kumari** [comment]
good work!!

**Pull request merged**
