### PR TITLE
Open multiple links automatically

### PR DESCRIPTION
**Pull request by nitinkumar30**
I've come up with an idea on **Automation with Python**.
Users can open multiple links with a single click with automation. It's another mini project which can be made to understand more about selenium & automation with any language. I've come up with Python.

The only thing is user has to install the module - `pip install selenium` which is important for automation.

Please tag this PR under 'Hacktober fest 2021'

### CODE REVIEW

**Comment by neha07kumari** [comment]
Do the needful for contributors.md file

**Comment by nitinkumar30** [comment]
> Do the needful for contributors.md file

Added my info in there. Thanks!

**Comment by neha07kumari** [comment]
but I'm not able to see the changes you made.
Please push the changes you did.

**Comment by neha07kumari** [comment]
Good work @nitinkumar30

**Comment by nitinkumar30** [comment]
> Good work @nitinkumar30

Thanks, @neha07kumari. Please go through the updated contributors.md file. Thanks!

**Pull request merged**
