### PR TITLE
Hardware and System Information using Python 💻

### PR DESCRIPTION
**Pull request by Somanyu**
This basic python script will tell us about our system and CPU which is vital for troubleshooting your PC. This will be helpful and save time as we don't have to search into various places in your control panel or ask for help in Google.

### CODE REVIEW

**Comment by neha07kumari** [comment]
@Somanyu  Read the rules & steps for contribution written in README.md
Open an issue before PR and once assigned then go for PR.

**Comment by neha07kumari** [comment]
@Somanyu  Please do the needful in the contibutors.md as required.

**Comment by Somanyu** [comment]
Added Name and Place in contributors.md as required.

**Comment by neha07kumari** [comment]
Do it again .
I cannot see any changes in it.

**Comment by neha07kumari** [comment]
Good work @Somanyu

**Comment by Somanyu** [comment]
Thank you @neha07kumari

**Pull request merged**
