### PR TITLE
Added Constellation and Waiter Problem python code

### PR DESCRIPTION
**Pull request by soupierbucket**
Hello Neha, I have made the said changes and added my name in the contributors.md file. I have added my code contribution for 2 issues raised, Constellation Problem and the Waiter problem. Please do the needful.

### CODE REVIEW

**Comment by neha07kumari** [comment]
good work!!

**Comment by soupierbucket** [comment]
Hello, had a query. I had added 2 different problem statement solution files in this push but on the hacktoberfest portal it is counting it as one. Do I need to make another pr for the same?

**Comment by neha07kumari** [comment]
yes it will count as one, because you made only 1 PR which included both the issues.
You should have made 2 different PRs.
Still you can go for other non-duplicate issues:)

**Comment by neha07kumari** [comment]
Please do not make another PR for the same issue as it has been merged.

**Comment by soupierbucket** [comment]
Okay, alright

**Pull request merged**
