### PR TITLE
Add random password generator

### PR DESCRIPTION
**Pull request by R055A**
# Random Password Generator

Generates random passwords of a specified or recommended minimum length

## Supported password types
- case-sensitive alphanumeric
- case-sensitive alphanumeric with special characters excluding space
- case-insensitive alphanumeric
- case-insensitive alphanumeric with special characters excluding space
 
#### If a password is not alphanumeric, no symbols in a subset share adjacency:
- ```X>1[g0J4Q-j%c+U|D^u/r<S```       (case-sensitive)
- ```2t1-0s$8f5v;9,r*e4@6:```                (case-insensitive)
- ```!B]6C3b+Q2H0v{1#F\7i9d|5R4```    (case-sensitive)

#### If a password is alphanumeric, symbols in a subset can share adjacency:
- ```bt90h76l3p```                        (case-insensitive)
- ```s0918o6x2ptwh3```               (case-insensitive)
- ```3wFyRHdOL40```                   (case-sensitive)

#### Brute-force attempts required to crack random passwords at length 12 when:
- case-insensitive alphanumeric (36 symbols):
    - over 300 million attempts, or half on average
- case-sensitive alphanumeric and special characters combined (95 symbols):
    - over 6 billion attempts, or half on average

#### To calculate brute-force attempts (or entropy) for a password: 
- password length * log2(symbol count)

## Commands:
- Specify a custom password length:         ```-l <password-length>```
- Generate alphanumeric password:          ```-an```
- Generate case-insensitive password:       ```-ci```

#### Example 1:
- input:
    - ```python3 random_password_generator.py```
- output:
    - ```Generated random password 1:  >U{0v2=y-3T%```
    - ```Generated random password 2:  1o7S2s4}5^h0```
    - ```Generated random password 3:  1#B5]9$r=7x3```
    
#### Example 2:
 - input:
     - ```python3 random_password_generator.py -l 20```
- output:
     - ```Generated random password 1:  2u|0x!7-s;1z*9H5~8P>```
     - ```Generated random password 2:  7q5<8G+1/P]6N3)h4t0|```
     - ```Generated random password 3:  9/Q+5;p%X6<d-8t7y!0B```
     
#### Example 3:
- input:
     - ```python3 random_password_generator.py -l 15 -an```
- output:
     - ```Generated random password 1:  6459Bj3s7JZIO0l```
     - ```Generated random password 2:  v0U3w4657y82Zd1```
     - ```Generated random password 3:  194ZI5837062fPG```

#### Example 4:
- input:
    - ```python3 random_password_generator.py -l 8 -ci```
- output:
     - ```Generated random password 1:  #0a1<7e&```
     - ```Generated random password 2:  e3]q7m0/```
     - ```Generated random password 3:  p8w5}6;o```

#### Example 5:
- input:
     - ```python3 random_password_generator.py -l 10 -an -ci```
- output:
     - ```Generated random password 1:  76y90253ji```
     - ```Generated random password 2:  lso7d296bq```
     - ```Generated random password 3:  56872eaq01```

#### Example 6:
- input:
    - ```python3 random_password_generator.py -an -ci```
- output:
     - ```Generated random password 1:  vx0mj3c5k79z```
     - ```Generated random password 2:  415s09vc832m```
     - ```Generated random password 3:  novxl5pr349m```

### CODE REVIEW

**Comment by neha07kumari** [comment]
@R055A  Sorry!! but you need to make an issue before any PR. Once the issue has been assigned to you then you can go for PR. The issue is also assigned in first come basis. I think I have made it clear. See you soon 🙂.

**Comment by R055A** [comment]
> 
> 
> @R055A Sorry!! but you need to make an issue before any PR. Once the issue has been assigned to you then you can go for PR. The issue is also assigned in first come basis. I think I have made it clear. See you soon 🙂.

Thank you for letting me know. I haven't seen any mention of this in the README.md file for this repository.

**Comment by neha07kumari** [comment]
Good Work @R055A  🎉

**Comment by R055A** [comment]
> 
> 
> Good Work @R055A 🎉

Thank you @neha07kumari

**Pull request merged**
